[package]
name = "hardware-logviewer"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capnp = "0.19"
clap = { version = "4", features = ["derive"] }

[build-dependencies]
capnpc = "0.19"